# Site settings
title: pdxrlang
motto: PDX R Group
email: myrmecocystus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: pdxrlang
github_username:  PortlandRUserGroup
permalink: /

# Build settings
markdown: kramdown
